controller_list:
  - name: fake_fl_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_shoulder
      - front_left_leg
      - front_left_foot
  - name: fake_fr_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - front_right_shoulder
      - front_right_leg
      - front_right_foot
  - name: fake_rl_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_left_shoulder
      - rear_left_leg
      - rear_left_foot
  - name: fake_rr_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_right_shoulder
      - rear_right_leg
      - rear_right_foot
  - name: fake_all_legs_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_shoulder
      - front_left_leg
      - front_left_foot
      - front_right_shoulder
      - front_right_leg
      - front_right_foot
      - rear_left_shoulder
      - rear_left_leg
      - rear_left_foot
      - rear_right_shoulder
      - rear_right_leg
      - rear_right_foot
  - name: fake_fl_foot_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_foot
  - name: fake_fr_foot_controller
    type: $(arg fake_execution_type)
    joints:
      - front_right_foot
  - name: fake_rl_foot_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_left_foot
  - name: fake_rr_foot_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_right_foot
initial:  # Define initial robot poses per group
  - group: all_legs
    pose: neutral